### ISSUE TITLE
Format dollar amounts

### ISSUE THREAD

**Issue by codegoalie** [davidkassa/dvc-rofr-stats#1096]
I find it easier to read larger dollar amounts if they have the dollar sign and are comma separated. I was thinking mainly in the data table and the Compare view:

![image](https://user-images.githubusercontent.com/75132/94846407-1b003e80-03ef-11eb-9857-961c022fde7a.png)

![image](https://user-images.githubusercontent.com/75132/94846437-22bfe300-03ef-11eb-91a4-e78789b08900.png)

As I mentioned on Reddit, I'd be happy to work on this. I cloned and got the project running last night.

Thanks!

**Comment by davidkassa** [comment]
excellent! PRs are very welcome and that sounds like a great one that's an
easy starting point.
